name: CD

# on: deployment
on: push

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Assert Linting
        shell: pwsh
        run: ./.github/scripts/Assert-Linting
      - name: Assert Tests
        shell: pwsh
        run: ./.github/scripts/Assert-Tests

  publish:
    needs: validate
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Publish Module
        shell: pwsh
        run: ./.github/scripts/Publish-Module
