name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        shell: pwsh
        run: ./.github/scripts/Install-Dependencies
      - name: Assert Linting
        shell: pwsh
        run: ./.github/scripts/Assert-Linting
      - name: Assert Tests
        shell: pwsh
        run: ./.github/scripts/Assert-Tests
