name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Lint
        use: pwsh
        run: ./.github/Assert-Linting
      - name: Test
        use: pwsh
        run: ./.github/Assert-Tests
