name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Debug
        run: |
          Write-Host "Buenos Dias!"
          Get-ChildItem -Recurse -File | % FullName
      - name: Lint
        run: ./.github/Assert-Linting
      - name: Test
        run: ./.github/Assert-Tests
