name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Lint
      run: ./.github/Assert-ValidStyle
    - name: Test
      run: ./.github/Assert-ValidTests
