name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Lint
        run: pwsh ./.github/scripts/Assert-Linting
      - name: Test
        run: pwsh ./.github/scripts/Assert-Tests
