name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Lint
        shell: pwsh
        run: ./.github/scripts/Assert-Linting
      - name: Test
        shell: pwsh
        run: ./.github/scripts/Assert-Tests
